version: '3'
services:
  nicofeed:
    build: 
      context: .
      dockerfile: ./apps/nicofeed/Dockerfile
    ports:
      - "3005:3000"
    environments:
      - ALLOW_USER_REGISTRATION=true
      - USER_REGISTRATION_PASSID=992d71d4-9157-4344-bc50-d0a2d8a4d2c4
    restart: always
    container_name: nicofeed

  nicofeed-fe:
    build: 
      context: .
      dockerfile: ./apps/nicofeed-fe/Dockerfile
    ports:
      - "4205:3000" 
    restart: always
    container_name: nicofeed-fe

volumes:
  postgres_data: