version: '3'
services:
  nicofeed:
    build: 
      context: .
      dockerfile: ./apps/nicofeed/Dockerfile
    ports:
      - "3005:3000" 
    restart: always
    container_name: nicofeed

  nicofeed-fe:
    build: 
      context: .
      dockerfile: ./apps/nicofeed-fe/Dockerfile
    ports:
      - "4205:3000" 
    restart: always
    container_name: nicofeed-fe

  db:
    image: postgres:17
    container_name: nicofeed_db
    environment:
      POSTGRES_USER: nicofeed
      POSTGRES_PASSWORD: nicofeed
      POSTGRES_DB: nicofeed
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: